[project]
name = "gator-quant-hacks"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "databento",
    "pandas",
    "numpy",
    "pydantic",
    "pyyaml",
    "python-dotenv",
    "vectorbt",
    "polars",
    "torch>=2.4.0",
    "triton>=3.0.0",
    "xgboost",
    "nautilus-trader[visualization]>=2.0.0rc5",
]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cuda" }]